-- --pomotion 테이블 생성
CREATE TABLE PROMOTION_BOARD (
    promotion_num NUMBER PRIMARY KEY,
    user_nick VARCHAR2(100) NOT NULL,
    promotion_title VARCHAR2(100) NOT NULL,
    promotion_content CLOB,
    promotion_create_date DATE DEFAULT SYSDATE NOT NULL,
    promotion_ofile VARCHAR2(200),
    promotion_sfile VARCHAR2(300),
    downcount NUMBER(5) DEFAULT 0 NOT NULL,
    visitcount NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_user_nick_promotion FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

--  ptomotion테이블시퀀스 생성
create sequence promotion_board_seq
increment by 1 
start with 1    
minvalue 1     
nomaxvalue      
nocycle        
nocache;        


-- promotion 댓글 생성
CREATE TABLE promotion_COMMENT (
    promotion_comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_num NUMBER NOT NULL,
    user_nick VARCHAR2(100) NOT NULL,
    promotion_comment_content VARCHAR2(1000) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_promotion_num FOREIGN KEY (promotion_num) REFERENCES promotion_BOARD(promotion_num)
    ON DELETE CASCADE,
    CONSTRAINT fk_user_nick_comment_promotion FOREIGN KEY (user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

--promotion 댓글 시퀀스생성
CREATE SEQUENCE promotion_comment_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--promotion 좋아요 테이블 생성
CREATE TABLE PROMOTION_LIKES (
    like_id NUMBER PRIMARY KEY,
    promotion_num NUMBER NOT NULL,
    user_nick VARCHAR2(100) NOT NULL,
    like_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_like_promotion FOREIGN KEY(promotion_num) REFERENCES PROMOTION_BOARD(promotion_num)
    ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

-- promotion 좋아요 시퀀스 생성
CREATE SEQUENCE promotion_likes_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;


-- PROMOTION_BOARD 테이블에 더미 데이터 삽입
INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user1', '신제품 런칭 이벤트', '우리 회사의 신제품을 소개합니다. 이번 주말 특별 할인 이벤트를 진행합니다!', SYSDATE, NULL, NULL, 0, 100);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user2', '여름맞이 특별 프로모션', '여름 시즌을 맞아 특별 프로모션을 진행합니다. 다양한 상품을 할인가로 만나보세요.', SYSDATE, NULL, NULL, 0, 80);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user3', '한정판 제품 소개', '한정판 제품이 출시되었습니다. 서두르세요! 수량이 한정되어 있습니다.', SYSDATE, NULL, NULL, 0, 150);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user4', '가을 컬렉션 런칭', '올 가을을 빛낼 컬렉션이 출시되었습니다. 지금 바로 확인해보세요!', SYSDATE, NULL, NULL, 0, 120);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user5', '겨울 세일 안내', '겨울 시즌 세일을 시작합니다. 최대 50% 할인을 놓치지 마세요.', SYSDATE, NULL, NULL, 0, 90);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user6', '크리스마스 이벤트', '크리스마스를 맞아 특별 이벤트를 준비했습니다. 선물을 받아가세요!', SYSDATE, NULL, NULL, 0, 130);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user7', '봄맞이 대바겐 세일', '봄 시즌 대바겐 세일이 시작되었습니다. 다양한 상품을 저렴하게 구매하세요.', SYSDATE, NULL, NULL, 0, 70);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user8', '신규 서비스 런칭', '새로운 서비스를 선보입니다. 특별한 혜택을 받아보세요.', SYSDATE, NULL, NULL, 0, 110);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user9', 'VIP 고객 감사 이벤트', 'VIP 고객만을 위한 특별한 혜택을 준비했습니다. 지금 확인해보세요!', SYSDATE, NULL, NULL, 0, 140);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user10', '여름 맞이 바캉스 준비물 세일', '여름 바캉스를 준비하셨나요? 필요한 모든 것을 저렴하게 준비하세요.', SYSDATE, NULL, NULL, 0, 95);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user1', '가정의 달 특별 이벤트', '5월 가정의 달을 맞이하여 전 상품을 특별 할인가로 제공 중입니다!', SYSDATE, NULL, NULL, 0, 160);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user2', '한여름 세일 시작!', '한여름을 맞아 특별 세일을 시작합니다. 지금 바로 할인 혜택을 받아보세요!', SYSDATE, NULL, NULL, 0, 180);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user3', '신규 고객 대상 웰컴 이벤트', '신규 고객님들을 위한 특별한 웰컴 이벤트! 신규 가입 후 특별 혜택을 받아보세요.', SYSDATE, NULL, NULL, 0, 90);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user4', '연말 결산 빅 세일', '2024년을 마무리하며, 연말 결산 빅 세일을 시작합니다. 최대 70% 할인!', SYSDATE, NULL, NULL, 0, 250);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user5', '가을 맞이 아웃도어 상품 대세일', '가을 아웃도어 캠핑 용품 대세일! 지금 할인된 가격으로 만나보세요.', SYSDATE, NULL, NULL, 0, 140);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user6', '할로윈 특가 세일!', '할로윈을 맞아 특가 세일을 진행합니다. 한정된 상품을 저렴하게 구매하세요!', SYSDATE, NULL, NULL, 0, 190);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user7', '신규 런칭 브랜드 소개', '새로운 브랜드를 런칭했습니다! 한정판 제품을 지금 바로 만나보세요.', SYSDATE, NULL, NULL, 0, 175);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user8', '디지털 제품 할인 이벤트', '최신 디지털 제품들을 특별 할인가에 제공 중입니다. 놓치지 마세요!', SYSDATE, NULL, NULL, 0, 200);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user9', '뷰티 제품 세일', '뷰티 제품 전 품목 30% 할인! 여름철 피부 관리, 지금 시작하세요.', SYSDATE, NULL, NULL, 0, 120);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user10', '학용품 특별 세일', '신학기 준비를 위한 학용품 세일을 진행 중입니다. 최대 40% 할인!', SYSDATE, NULL, NULL, 0, 150);

commit;


-- PROMOTION_BOARD 테이블에 더미 데이터 추가 삽입 (20개)
INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user1', '가정의 달 이벤트', '5월 가정의 달을 맞이하여 전 상품 특별 할인을 진행합니다!', SYSDATE, NULL, NULL, 0, 160);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user2', '한여름 세일', '한여름을 맞아 특별 세일을 진행합니다. 전 상품 최대 40% 할인!', SYSDATE, NULL, NULL, 0, 180);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user3', '신규 회원 특별 이벤트', '신규 회원 가입 시 추가 포인트 적립 혜택을 제공해드립니다.', SYSDATE, NULL, NULL, 0, 90);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user4', '연말 결산 빅 세일', '올해 마지막으로 진행하는 연말 결산 빅 세일! 전 상품 최대 50% 할인.', SYSDATE, NULL, NULL, 0, 200);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user5', '가을 컬렉션 출시', '올 가을을 빛낼 새로운 컬렉션을 출시했습니다. 지금 바로 만나보세요.', SYSDATE, NULL, NULL, 0, 150);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user6', '겨울 특별 프로모션', '겨울 시즌을 맞아 특별 프로모션을 진행합니다. 다양한 상품을 할인가로 만나보세요.', SYSDATE, NULL, NULL, 0, 140);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user7', '크리스마스 세일', '크리스마스를 맞아 전 상품 특별 세일을 진행합니다. 최대 50% 할인!', SYSDATE, NULL, NULL, 0, 190);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user8', '봄맞이 대바겐 세일', '봄 시즌 대바겐 세일! 다양한 제품을 저렴한 가격에 만나보세요.', SYSDATE, NULL, NULL, 0, 100);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user9', '신규 브랜드 런칭', '새로운 브랜드가 런칭되었습니다! 한정 상품을 놓치지 마세요.', SYSDATE, NULL, NULL, 0, 180);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user10', '여름 시즌 특별 기획전', '여름 시즌을 맞아 특별 기획전을 진행 중입니다. 다양한 상품을 할인된 가격에 만나보세요.', SYSDATE, NULL, NULL, 0, 95);

-- 추가 10개 더미 데이터 삽입
INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user1', '할로윈 특가 세일', '할로윈을 맞아 다양한 상품을 특가로 제공 중입니다. 서두르세요!', SYSDATE, NULL, NULL, 0, 130);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user2', '블랙 프라이데이 세일', '블랙 프라이데이를 맞아 대규모 세일을 진행합니다. 놓치지 마세요!', SYSDATE, NULL, NULL, 0, 220);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user3', '복합 쇼핑몰 그랜드 오픈', '새롭게 오픈한 복합 쇼핑몰에서 다양한 상품을 만나보세요. 오픈 기념 세일 중입니다.', SYSDATE, NULL, NULL, 0, 170);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user4', '여름 맞이 캠핑 용품 할인', '캠핑 용품을 여름 시즌에 맞춰 특별 할인가에 제공 중입니다.', SYSDATE, NULL, NULL, 0, 100);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user5', '스포츠 용품 세일', '스포츠 용품 전 품목을 할인된 가격으로 만나보세요. 여름 운동을 준비하세요!', SYSDATE, NULL, NULL, 0, 120);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user6', '한정판 굿즈 판매', '한정판 굿즈를 놓치지 마세요! 재고 소진 시 종료됩니다.', SYSDATE, NULL, NULL, 0, 140);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user7', '백화점 특별 세일', '백화점 전 상품을 최대 50% 할인된 가격으로 만나보세요.', SYSDATE, NULL, NULL, 0, 170);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user8', '신학기 맞이 학용품 할인', '신학기를 준비하는 학생들을 위한 특별 할인전! 학용품을 저렴하게 준비하세요.', SYSDATE, NULL, NULL, 0, 90);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user9', '전자제품 할인 이벤트', '최신 전자제품을 특별 할인가로 제공합니다. 지금 바로 구매하세요!', SYSDATE, NULL, NULL, 0, 210);

INSERT INTO PROMOTION_BOARD (promotion_num, user_nick, promotion_title, promotion_content, promotion_create_date, promotion_ofile, promotion_sfile, downcount, visitcount)
VALUES (promotion_board_seq.NEXTVAL, 'user10', '가구 할인 대전', '인테리어를 새롭게! 가구 할인 대전을 놓치지 마세요.', SYSDATE, NULL, NULL, 0, 200);

-- 테이블 내용 확인
SELECT * FROM PROMOTION_BOARD;

commit;